[2023-09-28 10:13:01,544] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (WARN) [SQL Error: 0, SQLState: 08S01] 
[2023-09-28 10:13:01,764] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (ERROR) [HikariPool-5 - Connection is not available, request timed out after 47105148ms.] 
[2023-09-28 10:13:01,765] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (ERROR) [Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.] 
[2023-09-28 10:13:10,978] - [com.zaxxer.hikari.pool.HikariPool] [run] -> (WARN) [HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=13h5m5s81ms267Âµs300ns).] 
[2023-09-28 10:13:01,766] - [org.camunda.bpm.engine.metrics] [logWarn] -> (WARN) [ENGINE-18001 Could not collect and log metrics] 
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:467) ~[spring-orm-5.3.22.jar:5.3.22]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.3.22.jar:5.3.22]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.3.22.jar:5.3.22]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137) ~[spring-tx-5.3.22.jar:5.3.22]
	at org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:71) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandCounterInterceptor.execute(CommandCounterInterceptor.java:35) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.ExceptionCodeInterceptor.execute(ExceptionCodeInterceptor.java:55) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.metrics.reporter.MetricsCollectionTask.collectMetrics(MetricsCollectionTask.java:76) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.metrics.reporter.MetricsCollectionTask.run(MetricsCollectionTask.java:53) ~[camunda-engine-7.18.0.jar:7.18.0]
	at java.util.TimerThread.mainLoop(Timer.java:566) ~[?:?]
	at java.util.TimerThread.run(Timer.java:516) ~[?:?]
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:276) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:284) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.22.jar:5.3.22]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.22.jar:5.3.22]
	... 12 more
Caused by: java.sql.SQLTransientConnectionException: HikariPool-5 - Connection is not available, request timed out after 47105148ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-4.0.3.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:276) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:284) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.22.jar:5.3.22]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.22.jar:5.3.22]
	... 12 more
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-4.0.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at jdk.internal.reflect.GeneratedConstructorAccessor151.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-4.0.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.UnknownHostException: No such host is known (freshersuperchargers.czbdrgtkozjs.us-east-1.rds.amazonaws.com)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1529) ~[?:?]
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1519) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1377) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1305) ~[?:?]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:130) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-4.0.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[2023-09-28 10:14:05,414] - [com.zaxxer.hikari.pool.HikariPool] [run] -> (WARN) [HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=54s435ms791Âµs).] 
[2023-09-28 10:38:09,520] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7ce2d539 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 10:38:09,522] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (WARN) [SQL Error: 0, SQLState: 08003] 
[2023-09-28 10:38:09,522] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (ERROR) [HikariPool-5 - Connection is not available, request timed out after 849546ms.] 
[2023-09-28 10:38:09,523] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (ERROR) [No operations allowed after connection closed.] 
[2023-09-28 10:38:09,524] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [fetchTask] -> (ERROR) [Exception occured, Unable to perform Scheduler Task ] 
[2023-09-28 10:38:10,042] - [com.zaxxer.hikari.pool.HikariPool] [run] -> (WARN) [HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=14m34s517ms428Âµs).] 
[2023-09-28 10:38:57,755] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@52a39ccf (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 10:38:58,062] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@25b34763 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 10:38:58,369] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7479fe50 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 10:38:58,646] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3a7241f4 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 10:38:58,874] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@53b64c88 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 10:38:59,112] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6c0181c2 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 10:38:59,393] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@57b1696c (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 10:38:59,701] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7fe4ef8f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 10:38:59,920] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1e572ef7 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 11:10:02,599] - [com.zaxxer.hikari.pool.HikariPool] [run] -> (WARN) [HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=21m52s369ms140Âµs700ns).] 
[2023-09-28 12:14:43,256] - [com.zaxxer.hikari.pool.HikariPool] [run] -> (WARN) [HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=8m40s556ms693Âµs100ns).] 
[2023-09-28 14:37:39,187] - [com.zaxxer.hikari.pool.HikariPool] [run] -> (WARN) [HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=49m55s776ms723Âµs700ns).] 
[2023-09-28 17:42:37,632] - [com.zaxxer.hikari.pool.HikariPool] [run] -> (WARN) [HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=38m58s187ms374Âµs800ns).] 
[2023-09-28 18:41:57,175] - [com.zaxxer.hikari.pool.HikariPool] [run] -> (WARN) [HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=21m49s515ms952Âµs100ns).] 
[2023-09-28 18:42:19,712] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@43e8930b (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 18:42:19,946] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@16e0fd70 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 18:42:20,206] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@16584c01 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 18:42:20,492] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6b28ccd9 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 18:42:20,755] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6cdf7a7c (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 21:59:42,163] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@62eeb201 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 21:59:42,165] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6b284164 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 21:59:42,167] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@67af0e50 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 21:59:42,168] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7046d61e (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 21:59:42,170] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@48460236 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 21:59:42,190] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@38bed935 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 21:59:42,192] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@40912ba6 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 21:59:42,193] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4397a71e (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 21:59:42,195] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4da171d6 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 21:59:42,208] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3987e26 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 22:12:03,456] - [com.zaxxer.hikari.pool.HikariPool] [run] -> (WARN) [HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=3h12m42s427ms671Âµs900ns).] 
[2023-09-28 23:24:41,912] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1856dcf8 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-09-28 23:24:42,109] - [com.zaxxer.hikari.pool.HikariPool] [run] -> (WARN) [HikariPool-5 - Thread starvation or clock leap detected (housekeeper delta=21m8s512ms65Âµs600ns).] 
[2023-09-28 23:24:42,329] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-5 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3eaa1af5 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
