[2023-08-03 11:37:03,634] - [org.hibernate.validator.internal.util.Version] [<clinit>] -> (INFO) [HV000001: Hibernate Validator 6.2.5.Final] 
[2023-08-03 11:37:03,723] - [com.hcl.elch.freshersuperchargers.trainingworkflow.TrainingWorkflowApplication] [logStarting] -> (INFO) [Starting TrainingWorkflowApplication using Java 17.0.4.1 on LP-5CG0471VCD with PID 22752 (C:\Users\tausif.ahmad\Downloads\FresherSuperChargers\FresherSuperChargers\target\classes started by tausif.ahmad in C:\Users\tausif.ahmad\Downloads\FresherSuperChargers\FresherSuperChargers)] 
[2023-08-03 11:37:03,733] - [com.hcl.elch.freshersuperchargers.trainingworkflow.TrainingWorkflowApplication] [logStartupProfileInfo] -> (INFO) [No active profile set, falling back to 1 default profile: "default"] 
[2023-08-03 11:37:03,848] - [org.springframework.boot.devtools.restart.ChangeableUrls] [logTo] -> (INFO) [The Class-Path manifest attribute in C:\Users\tausif.ahmad\.m2\repository\org\glassfish\hk2\hk2\2.6.1\hk2-2.6.1.jar referenced one or more files that do not exist: file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/hk2-utils.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/jakarta.annotation-api.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/jakarta.inject.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/hk2-api.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/aopalliance-repackaged.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/hk2-core.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/hk2-locator.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/javassist.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/hk2-runlevel.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/class-model.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/asm.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/asm-analysis.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/asm-commons.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/asm-tree.jar,file:/C:/Users/tausif.ahmad/.m2/repository/org/glassfish/hk2/hk2/2.6.1/asm-util.jar] 
[2023-08-03 11:37:03,850] - [org.springframework.boot.devtools.env.DevToolsPropertyDefaultsPostProcessor] [logTo] -> (INFO) [Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable] 
[2023-08-03 11:37:03,850] - [org.springframework.boot.devtools.env.DevToolsPropertyDefaultsPostProcessor] [logTo] -> (INFO) [For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'] 
[2023-08-03 11:37:05,809] - [org.springframework.data.repository.config.RepositoryConfigurationDelegate] [registerRepositoriesIn] -> (INFO) [Bootstrapping Spring Data JPA repositories in DEFAULT mode.] 
[2023-08-03 11:37:06,025] - [org.springframework.data.repository.config.RepositoryConfigurationDelegate] [registerRepositoriesIn] -> (INFO) [Finished Spring Data repository scanning in 197 ms. Found 9 JPA repository interfaces.] 
[2023-08-03 11:37:07,573] - [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] [initialize] -> (INFO) [Tomcat initialized with port(s): 9002 (http)] 
[2023-08-03 11:37:07,595] - [org.apache.coyote.http11.Http11NioProtocol] [log] -> (INFO) [Initializing ProtocolHandler ["http-nio-9002"]] 
[2023-08-03 11:37:07,596] - [org.apache.catalina.core.StandardService] [log] -> (INFO) [Starting service [Tomcat]] 
[2023-08-03 11:37:07,597] - [org.apache.catalina.core.StandardEngine] [log] -> (INFO) [Starting Servlet engine: [Apache Tomcat/9.0.65]] 
[2023-08-03 11:37:08,837] - [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] [log] -> (INFO) [Initializing Spring embedded WebApplicationContext] 
[2023-08-03 11:37:08,838] - [org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext] [prepareWebApplicationContext] -> (INFO) [Root WebApplicationContext: initialization completed in 4986 ms] 
[2023-08-03 11:37:08,899] - [org.camunda.bpm.spring.boot.starter.rest.CamundaJerseyResourceConfig] [registerCamundaRestResources] -> (INFO) [Configuring camunda rest api.] 
[2023-08-03 11:37:08,944] - [org.camunda.bpm.spring.boot.starter.rest.CamundaJerseyResourceConfig] [registerCamundaRestResources] -> (INFO) [Finished configuring camunda rest api.] 
[2023-08-03 11:37:09,584] - [org.hibernate.jpa.internal.util.LogHelper] [logPersistenceUnitInformation] -> (INFO) [HHH000204: Processing PersistenceUnitInfo [name: default]] 
[2023-08-03 11:37:09,727] - [org.hibernate.Version] [logVersion] -> (INFO) [HHH000412: Hibernate ORM core version 5.6.11.Final] 
[2023-08-03 11:37:10,098] - [org.hibernate.annotations.common.Version] [<clinit>] -> (INFO) [HCANN000001: Hibernate Commons Annotations {5.1.2.Final}] 
[2023-08-03 11:37:10,347] - [com.zaxxer.hikari.HikariDataSource] [getConnection] -> (INFO) [HikariPool-1 - Starting...] 
[2023-08-03 11:37:14,395] - [com.zaxxer.hikari.HikariDataSource] [getConnection] -> (INFO) [HikariPool-1 - Start completed.] 
[2023-08-03 11:37:14,444] - [org.hibernate.dialect.Dialect] [<init>] -> (INFO) [HHH000400: Using dialect: org.hibernate.dialect.MySQL5InnoDBDialect] 
[2023-08-03 11:37:23,773] - [org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator] [initiateService] -> (INFO) [HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]] 
[2023-08-03 11:37:23,790] - [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean] [buildNativeEntityManagerFactory] -> (INFO) [Initialized JPA EntityManagerFactory for persistence unit 'default'] 
[2023-08-03 11:37:24,096] - [org.camunda.bpm.spring.boot] [logInfo] -> (INFO) [STARTER-SB040 Setting up jobExecutor with corePoolSize=3, maxPoolSize:10] 
[2023-08-03 11:37:24,296] - [org.camunda.bpm.engine.cfg] [logInfo] -> (INFO) [ENGINE-12003 Plugin 'CompositeProcessEnginePlugin[genericPropertiesConfiguration, camundaProcessEngineConfiguration, camundaDatasourceConfiguration, camundaJpaConfiguration, camundaJobConfiguration, camundaHistoryConfiguration, camundaMetricsConfiguration, camundaAuthorizationConfiguration, CreateAdminUserConfiguration[adminUser=AdminUserProperty[id=Test, firstName=Test, lastName=Test, email=Test@localhost, password=******]], failedJobConfiguration, disableDeploymentResourcePattern, eventPublisherPlugin, ApplicationContextClassloaderSwitchPlugin, SpringBootSpinProcessEnginePlugin]' activated on process engine 'default'] 
[2023-08-03 11:37:24,309] - [org.camunda.bpm.spring.boot] [logInfo] -> (INFO) [STARTER-SB020 ProcessApplication enabled: autoDeployment via springConfiguration#deploymentResourcePattern is disabled] 
[2023-08-03 11:37:24,311] - [org.camunda.bpm.spring.boot.starter.event.EventPublisherPlugin] [preInit] -> (INFO) [EVENTING-001: Initialized Camunda Spring Boot Eventing Engine Plugin.] 
[2023-08-03 11:37:24,311] - [org.camunda.bpm.spring.boot.starter.event.EventPublisherPlugin] [preInit] -> (INFO) [EVENTING-003: Task events will be published as Spring Events.] 
[2023-08-03 11:37:24,312] - [org.camunda.bpm.spring.boot.starter.event.EventPublisherPlugin] [preInit] -> (INFO) [EVENTING-005: Execution events will be published as Spring Events.] 
[2023-08-03 11:37:24,316] - [org.camunda.bpm.spring.boot.starter.event.EventPublisherPlugin] [preInit] -> (INFO) [EVENTING-007: History events will be published as Spring events.] 
[2023-08-03 11:37:24,326] - [org.camunda.spin] [logInfo] -> (INFO) [SPIN-01010 Discovered Spin data format provider: org.camunda.spin.impl.json.jackson.format.JacksonJsonDataFormatProvider[name = application/json]] 
[2023-08-03 11:37:24,798] - [org.camunda.spin] [logInfo] -> (INFO) [SPIN-01010 Discovered Spin data format provider: org.camunda.spin.impl.xml.dom.format.DomXmlDataFormatProvider[name = application/xml]] 
[2023-08-03 11:37:24,951] - [org.camunda.spin] [logInfo] -> (INFO) [SPIN-01009 Discovered Spin data format: org.camunda.spin.impl.xml.dom.format.DomXmlDataFormat[name = application/xml]] 
[2023-08-03 11:37:24,952] - [org.camunda.spin] [logInfo] -> (INFO) [SPIN-01009 Discovered Spin data format: org.camunda.spin.impl.json.jackson.format.JacksonJsonDataFormat[name = application/json]] 
[2023-08-03 11:37:25,389] - [org.camunda.bpm.dmn.feel.scala] [logInfo] -> (INFO) [FEEL/SCALA-01001 Spin value mapper detected] 
[2023-08-03 11:37:25,524] - [org.camunda.feel.FeelEngine] [<init>] -> (INFO) [Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.feel.impl.JavaValueMapper@4733e0cc, org.camunda.spin.plugin.impl.feel.integration.SpinValueMapper@5631069b)), function-provider: org.camunda.bpm.dmn.feel.impl.scala.function.CustomFunctionTransformer@52b0e3ac, clock: SystemClock, configuration: Configuration(false)]] 
[2023-08-03 11:37:33,076] - [org.camunda.bpm.connect] [logInfo] -> (INFO) [CNCT-01004 Discovered provider for connector id 'http-connector' and class 'org.camunda.connect.httpclient.impl.HttpConnectorImpl': 'org.camunda.connect.httpclient.impl.HttpConnectorProviderImpl'] 
[2023-08-03 11:37:33,082] - [org.camunda.bpm.connect] [logInfo] -> (INFO) [CNCT-01004 Discovered provider for connector id 'soap-http-connector' and class 'org.camunda.connect.httpclient.soap.impl.SoapHttpConnectorImpl': 'org.camunda.connect.httpclient.soap.impl.SoapHttpConnectorProviderImpl'] 
[2023-08-03 11:37:43,362] - [org.camunda.bpm.engine] [logInfo] -> (INFO) [ENGINE-00001 Process Engine default created.] 
[2023-08-03 11:37:45,613] - [org.camunda.bpm.spring.boot] [logInfo] -> (INFO) [STARTER-SB011 Skip creating initial Admin User, user does exist: UserEntity[id=Test, revision=1, firstName=Test, lastName=Test, email=Test@localhost, password={SHA-512}qaaod5sQzlNBX/DtkFXV2Wtk8JFgT7Sj5fESaYk+nEvrAaXdTQt9ciqlrYrvTsSbcsJ3q7r9e7fzAGkK8ePNCQ==, salt=jinu/MNTKMO3yXaPnYXLOA==, lockExpirationTime=null, attempts=0]] 
[2023-08-03 11:37:46,060] - [org.drools.compiler.kie.builder.impl.KieBuilderImpl] [packageNameForFile] -> (WARN) [File 'rules/tasks.drl' is in folder 'rules' but declares package 'com.foobat'. It is advised to have a correspondance between package and folder names.] 
[2023-08-03 11:37:47,616] - [org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration] [openEntityManagerInViewInterceptor] -> (WARN) [spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning] 
[2023-08-03 11:37:48,230] - [org.camunda.bpm.spring.boot.starter.webapp.filter.LazyInitRegistration] [lazyInit] -> (INFO) [lazy initialized org.camunda.bpm.spring.boot.starter.webapp.filter.LazySecurityFilter@64405ea0] 
[2023-08-03 11:37:48,232] - [org.camunda.bpm.spring.boot.starter.webapp.filter.LazyInitRegistration] [lazyInit] -> (INFO) [lazy initialized org.camunda.bpm.spring.boot.starter.webapp.filter.LazyProcessEnginesFilter@6fb5a3b8] 
[2023-08-03 11:37:48,708] - [org.springframework.boot.devtools.autoconfigure.OptionalLiveReloadServer] [startServer] -> (INFO) [LiveReload server is running on port 35729] 
[2023-08-03 11:37:48,772] - [org.apache.coyote.http11.Http11NioProtocol] [log] -> (INFO) [Starting ProtocolHandler ["http-nio-9002"]] 
[2023-08-03 11:37:48,847] - [org.springframework.boot.web.embedded.tomcat.TomcatWebServer] [start] -> (INFO) [Tomcat started on port(s): 9002 (http) with context path ''] 
[2023-08-03 11:37:48,894] - [org.camunda.bpm.container] [logInfo] -> (INFO) [ENGINE-08024 Found processes.xml file at file:/C:/Users/tausif.ahmad/Downloads/FresherSuperChargers/FresherSuperChargers/target/classes/META-INF/processes.xml] 
[2023-08-03 11:37:49,021] - [org.camunda.bpm.container] [logInfo] -> (INFO) [ENGINE-08023 Deployment summary for process archive 'trainingWorkflowApplication': 

        userform.form
        training-workflow.bpmn
        userformPOC.form
] 
[2023-08-03 11:37:52,905] - [org.camunda.bpm.application] [logInfo] -> (INFO) [ENGINE-07021 ProcessApplication 'trainingWorkflowApplication' registered for DB deployments [fb8a2f46-3117-11ee-9d17-fa89d2161e61]. Will execute process definitions 

        Decision[version: 1, id: Decision:1:fbb6485a-3117-11ee-9d17-fa89d2161e61]
Deployment does not provide any case definitions.] 
[2023-08-03 11:37:53,454] - [org.camunda.bpm.container] [logInfo] -> (INFO) [ENGINE-08050 Process application trainingWorkflowApplication successfully deployed] 
[2023-08-03 11:37:53,463] - [com.hcl.elch.freshersuperchargers.trainingworkflow.TrainingWorkflowApplication] [logStarted] -> (INFO) [Started TrainingWorkflowApplication in 50.47 seconds (JVM running for 56.183)] 
[2023-08-03 11:37:53,471] - [org.camunda.bpm.engine.jobexecutor] [logInfo] -> (INFO) [ENGINE-14014 Starting up the JobExecutor[org.camunda.bpm.engine.spring.components.jobexecutor.SpringJobExecutor].] 
[2023-08-03 11:37:53,476] - [org.camunda.bpm.engine.jobexecutor] [logInfo] -> (INFO) [ENGINE-14018 JobExecutor[org.camunda.bpm.engine.spring.components.jobexecutor.SpringJobExecutor] starting to acquire jobs] 
[2023-08-03 11:38:02,223] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [getDetails] -> (INFO) [Start Event Connected] 
[2023-08-03 11:38:08,045] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [execute] -> (INFO) [In Service task to send EmailId] 
[2023-08-03 11:38:09,617] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [camundaTask] -> (INFO) [User EMAIL :- sarajaved09@gmail.com Username :- Sara Javed] 
[2023-08-03 11:38:09,916] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [execute] -> (INFO) [Processing] 
[2023-08-03 11:38:31,372] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.ServiceFinalTask] [execute] -> (INFO) [/////////////////////Final Service task///////////////////] 
[2023-08-03 11:38:32,858] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [Inside else ] 
[2023-08-03 11:38:33,456] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [value of  p :- [ProjectWorkflow(Id=1, Name=NEW_HIRE, user=User(email=sarajaved09@gmail.com, sapId=52070399, name=Sara Javed, contactNo=7454909729, alternateContactNo=null, address=null, gender=Gender(uid=null, key=FEMALE, value=Female), state=State(uid=26, key=IN-UP, value=Uttar Pradesh), region=Region(uid=1, key=NORTH, value=North), sheetCode=Non-Tier1, ProjAssignedStatus=true, category=Category(userId=3, category=non-tier1-cs)), taskId=1), ProjectWorkflow(Id=2, Name=SPRINGBOO, user=User(email=sarajaved09@gmail.com, sapId=52070399, name=Sara Javed, contactNo=7454909729, alternateContactNo=null, address=null, gender=Gender(uid=null, key=FEMALE, value=Female), state=State(uid=26, key=IN-UP, value=Uttar Pradesh), region=Region(uid=1, key=NORTH, value=North), sheetCode=Non-Tier1, ProjAssignedStatus=true, category=Category(userId=3, category=non-tier1-cs)), taskId=2)]] 
[2023-08-03 11:38:33,458] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [M Value NEW_HIRE Task Value NEW_HIRE] 
[2023-08-03 11:38:33,458] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [S valueSPRINGBOO] 
[2023-08-03 11:38:33,460] - [org.drools.compiler.kie.builder.impl.KieContainerImpl] [createKieBase] -> (INFO) [Start creation of KieBase: defaultKieBase] 
[2023-08-03 11:38:33,614] - [org.drools.compiler.kie.builder.impl.KieContainerImpl] [createKieBase] -> (INFO) [End creation of KieBase: defaultKieBase] 
[2023-08-03 11:38:33,974] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [Modules form database is :- Modules(moduleId=1, moduleName=NEW_HIRE, Exam=0, groupId=null, duration=5, POC=0)] 
[2023-08-03 11:38:34,251] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [Caught the Drools Exception] 
[2023-08-03 11:38:34,544] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.ServiceFinalTask] [nextTask] -> (INFO) [Unable to move to next Taskcom.hcl.elch.freshersuperchargers.trainingworkflow.exceptions.DroolsEngineException: Unable to perform the Drools Task,Because of drl file] 
[2023-08-03 11:38:34,545] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.ServiceFinalTask] [execute] -> (INFO) [Current task obj from ServiceFinalTask :- Task(id=0, taskId=1, userId=52070399, task=NEW_HIRE, Status=Processing, duedate=2023-07-15, approver=null)] 
[2023-08-03 11:38:34,546] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.ServiceFinalTask] [execute] -> (INFO) [An Exception from Final Service Task Due to ] 
[2023-08-03 11:38:34,834] - [org.camunda.bpm.engine.bpmn.behavior] [logInfo] -> (INFO) [ENGINE-02001 Execution with id 'Activity_1nfawup' throws an error event with errorCode 'Camunda Exception', but no catching boundary event was defined. Execution is ended (none end event semantics).] 
[2023-08-03 11:41:02,452] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [getDetails] -> (INFO) [Start Event Connected] 
[2023-08-03 11:41:04,649] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [execute] -> (INFO) [In Service task to send EmailId] 
[2023-08-03 11:41:06,036] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [camundaTask] -> (INFO) [User EMAIL :- sarajaved09@gmail.com Username :- Sara Javed] 
[2023-08-03 11:41:06,324] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [execute] -> (INFO) [Processing] 
[2023-08-03 11:41:27,480] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.ServiceFinalTask] [execute] -> (INFO) [/////////////////////Final Service task///////////////////] 
[2023-08-03 11:41:28,912] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [Inside else ] 
[2023-08-03 11:41:29,475] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [value of  p :- [ProjectWorkflow(Id=1, Name=NEW_HIRE, user=User(email=sarajaved09@gmail.com, sapId=52070399, name=Sara Javed, contactNo=7454909729, alternateContactNo=null, address=null, gender=Gender(uid=null, key=FEMALE, value=Female), state=State(uid=26, key=IN-UP, value=Uttar Pradesh), region=Region(uid=1, key=NORTH, value=North), sheetCode=Non-Tier1, ProjAssignedStatus=true, category=Category(userId=3, category=non-tier1-cs)), taskId=1), ProjectWorkflow(Id=2, Name=SPRINGBOOT, user=User(email=sarajaved09@gmail.com, sapId=52070399, name=Sara Javed, contactNo=7454909729, alternateContactNo=null, address=null, gender=Gender(uid=null, key=FEMALE, value=Female), state=State(uid=26, key=IN-UP, value=Uttar Pradesh), region=Region(uid=1, key=NORTH, value=North), sheetCode=Non-Tier1, ProjAssignedStatus=true, category=Category(userId=3, category=non-tier1-cs)), taskId=2)]] 
[2023-08-03 11:41:29,476] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [M Value NEW_HIRE Task Value NEW_HIRE] 
[2023-08-03 11:41:29,476] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [S valueSPRINGBOOT] 
[2023-08-03 11:41:29,767] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [Modules form database is :- Modules(moduleId=1, moduleName=NEW_HIRE, Exam=0, groupId=null, duration=5, POC=0)] 
[2023-08-03 11:41:30,045] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [next module 15 SPRINGBOOT] 
[2023-08-03 11:41:30,113] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [New value :-Task(id=0, taskId=2, userId=52070399, task=SPRINGBOOT, Status=InProgress, duedate=2023-08-18, approver=null)] 
[2023-08-03 11:41:30,390] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [setComplete] -> (INFO) [Completed] 
[2023-08-03 11:41:30,391] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [setComplete] -> (INFO) [Approver Name null] 
[2023-08-03 11:41:30,391] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [save] -> (INFO) [InProgress] 
[2023-08-03 11:41:30,734] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.ServiceFinalTask] [execute] -> (INFO) [Current task obj from ServiceFinalTask :- Task(id=0, taskId=1, userId=52070399, task=NEW_HIRE, Status=Completed, duedate=2023-07-15, approver=null)] 
[2023-08-03 11:41:30,734] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.ServiceFinalTask] [execute] -> (INFO) [Next task obj from ServiceFinalTask :- Task(id=16, taskId=2, userId=52070399, task=SPRINGBOOT, Status=InProgress, duedate=2023-08-18, approver=null)] 
[2023-08-03 11:41:30,736] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.EmailSenderService] [mailSendingForNextTask] -> (INFO) [Inside the mailSendingForNextTask() method now........] 
[2023-08-03 11:41:31,295] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.EmailSenderService] [mailSendingForNextTask] -> (INFO) [Exception encountered while sending next task mail..] 
[2023-08-03 11:42:31,541] - [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] [log] -> (INFO) [Initializing Spring DispatcherServlet 'dispatcherServlet'] 
[2023-08-03 11:42:31,542] - [org.springframework.web.servlet.DispatcherServlet] [initServletBean] -> (INFO) [Initializing Servlet 'dispatcherServlet'] 
[2023-08-03 11:42:31,546] - [org.springframework.web.servlet.DispatcherServlet] [initServletBean] -> (INFO) [Completed initialization in 4 ms] 
[2023-08-03 11:42:31,896] - [org.apache.catalina.util.SessionIdGeneratorBase] [log] -> (WARN) [Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [252] milliseconds.] 
[2023-08-03 11:44:09,055] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@192f390f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:44:09,470] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@6be73ed8 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:44:09,881] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@b6085ea (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:44:10,360] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@445f7d4b (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:44:10,765] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1b98bfac (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:44:34,268] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@5944a54f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:44:47,986] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@374a6c02 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:52:43,697] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@65fd494e (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:53:02,650] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [getDetails] -> (INFO) [Start Event Connected] 
[2023-08-03 11:53:03,226] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@391a8477 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:53:05,223] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [execute] -> (INFO) [In Service task to send EmailId] 
[2023-08-03 11:53:06,633] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [camundaTask] -> (INFO) [User EMAIL :- rahul18q61@gmail.com Username :- Rahul.Ganji] 
[2023-08-03 11:53:06,800] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@60c06e1d (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:53:06,909] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [execute] -> (INFO) [Processing] 
[2023-08-03 11:53:07,065] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@42c81be0 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:53:07,510] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@17f7d095 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:53:07,832] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3bdab39 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:53:08,306] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@606e9dd5 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:53:08,786] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@62fb9d23 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 11:53:27,603] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.ServiceFinalTask] [execute] -> (INFO) [/////////////////////Final Service task///////////////////] 
[2023-08-03 11:53:29,235] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [[workflow(Id=5, Name=NEW_HIRE, category=3, taskId=1), workflow(Id=6, Name=DATABASE, category=3, taskId=2)]] 
[2023-08-03 11:53:29,236] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [M Value NEW_HIRE Task Value NEW_HIRE] 
[2023-08-03 11:53:29,236] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [non-tier1-cs category 3] 
[2023-08-03 11:53:29,533] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [Modules form database is :- Modules(moduleId=1, moduleName=NEW_HIRE, Exam=0, groupId=null, duration=5, POC=0)] 
[2023-08-03 11:53:29,801] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [next module 10 DATABASE] 
[2023-08-03 11:53:29,804] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [getStatus] -> (INFO) [New value :-Task(id=0, taskId=2, userId=52126676, task=DATABASE, Status=InProgress, duedate=2023-08-13, approver=null)] 
[2023-08-03 11:53:30,089] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [setComplete] -> (INFO) [Completed] 
[2023-08-03 11:53:30,089] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [setComplete] -> (INFO) [Approver Name null] 
[2023-08-03 11:53:30,090] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.SchedulerServiceImpl] [save] -> (INFO) [InProgress] 
[2023-08-03 11:53:30,351] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.ServiceFinalTask] [execute] -> (INFO) [Current task obj from ServiceFinalTask :- Task(id=0, taskId=1, userId=52126676, task=NEW_HIRE, Status=Completed, duedate=2023-07-31, approver=null)] 
[2023-08-03 11:53:30,352] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.ServiceFinalTask] [execute] -> (INFO) [Next task obj from ServiceFinalTask :- Task(id=17, taskId=2, userId=52126676, task=DATABASE, Status=InProgress, duedate=2023-08-13, approver=null)] 
[2023-08-03 11:53:30,352] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.EmailSenderService] [mailSendingForNextTask] -> (INFO) [Inside the mailSendingForNextTask() method now........] 
[2023-08-03 11:53:31,131] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.EmailSenderService] [mailSendingForNextTask] -> (INFO) [Exception encountered while sending next task mail..] 
[2023-08-03 11:56:02,429] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [getDetails] -> (INFO) [Start Event Connected] 
[2023-08-03 11:56:04,821] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [execute] -> (INFO) [In Service task to send EmailId] 
[2023-08-03 11:56:06,208] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [camundaTask] -> (INFO) [User EMAIL :- rahul18q61@gmail.com Username :- Rahul.Ganji] 
[2023-08-03 11:56:06,500] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskController] [execute] -> (INFO) [Processing] 
[2023-08-03 11:56:28,688] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.JavaEmailSending] [execute] -> (INFO) [This is Email Sending Task about status] 
[2023-08-03 11:56:28,689] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.JavaEmailSending] [execute] -> (INFO) [ Branch Names : 52126676DATABASE] 
[2023-08-03 11:56:28,962] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.JavaEmailSending] [execute] -> (INFO) [Assesment Link :- exam_link] 
[2023-08-03 11:56:28,963] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.EmailSenderService] [mailSendingForTask] -> (INFO) [Inside the mailSendingForTask() method now........] 
[2023-08-03 11:56:29,100] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.EmailSenderService] [mailSendingForTask] -> (INFO) [Exception encountered while sending task mail..] 
[2023-08-03 11:57:15,858] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskAssignmentListener] [notify] -> (INFO) [//////////////This is the SME/Approver task///////////////////] 
[2023-08-03 11:57:16,181] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskAssignmentListener] [notify] -> (INFO) [Variables : 2] 
[2023-08-03 11:57:16,501] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskAssignmentListener] [notify] -> (INFO) [Group users [UserEntity[id=Sandipan, revision=1, firstName=Sandipan, lastName=Dandapat, email=sandipan.dandapat@hcl.com, password={SHA-512}kQ6NA9QbbGTtly4WgYV8OS0pvm3X04jeAeWiHQEwbCzUh8fU4AOFAUAv6x9Q4HrIvSwW8GZD9N1SvvumSU8OCQ==, salt=2r++8UMO/XZkQ4j8IDMIEA==, lockExpirationTime=null, attempts=0]]] 
[2023-08-03 11:57:16,502] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskAssignmentListener] [notify] -> (INFO) [Assignees :Sandipan] 
[2023-08-03 11:57:16,503] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskAssignmentListener] [notify] -> (INFO) [Assignees Mail :sandipan.dandapat@hcl.com] 
[2023-08-03 11:57:16,504] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskAssignmentListener] [notify] -> (INFO) [Recipient :[sandipan.dandapat@hcl.com]] 
[2023-08-03 11:57:16,504] - [com.hcl.elch.freshersuperchargers.trainingworkflow.controller.TaskAssignmentListener] [notify] -> (INFO) [Approval url :- http://35.169.136.179:9002/camunda/app/tasklist/default/#/task=c9e3343c-31c6-11ee-8966-085bd6a1e528] 
[2023-08-03 11:57:16,504] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.EmailSenderService] [mailSendingToApprover] -> (INFO) [Inside the mailSendingToApprover() method now........] 
[2023-08-03 11:57:16,505] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.EmailSenderService] [mailSendingToApprover] -> (INFO) [Task name :- DATABASE] 
[2023-08-03 11:57:17,263] - [com.hcl.elch.freshersuperchargers.trainingworkflow.service.EmailSenderService] [mailSendingToApprover] -> (INFO) [Exception encountered while sending mail to Approver..] 
[2023-08-03 12:17:16,879] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7703ec00 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:17:16,879] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@69ffc542 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:17:16,879] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1059dc99 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:17:16,882] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@38b018c0 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:17:16,882] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1edb1b89 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:17:17,326] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1be4553a (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:17:17,330] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@604e93c8 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:17:17,334] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@26adbe9b (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:22:43,854] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@41bfbee4 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:23:00,486] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@15a6e16a (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:23:00,969] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@1d54fff (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:23:08,730] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@25478e3a (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:23:10,681] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7fdbe926 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:23:13,358] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@54dafb95 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:23:19,314] - [org.springframework.boot.admin.SpringApplicationAdminMXBeanRegistrar$SpringApplicationAdmin] [shutdown] -> (INFO) [Application shutdown requested.] 
[2023-08-03 12:23:20,376] - [org.springframework.boot.admin.SpringApplicationAdminMXBeanRegistrar$SpringApplicationAdmin] [shutdown] -> (INFO) [Application shutdown requested.] 
[2023-08-03 12:23:20,599] - [org.springframework.boot.admin.SpringApplicationAdminMXBeanRegistrar$SpringApplicationAdmin] [shutdown] -> (INFO) [Application shutdown requested.] 
[2023-08-03 12:23:23,362] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4d75896a (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:23:24,572] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@2e7eee75 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:23:24,883] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@3b442d08 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:23:34,887] - [com.zaxxer.hikari.pool.PoolBase] [isConnectionAlive] -> (WARN) [HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@39a10e81 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.] 
[2023-08-03 12:23:38,506] - [com.zaxxer.hikari.pool.ProxyConnection] [checkException] -> (WARN) [HikariPool-1 - Connection com.mysql.cj.jdbc.ConnectionImpl@6e77f7fc marked as broken because of SQLSTATE(08S01), ErrorCode(0)] 
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 2,881 milliseconds ago. The last packet sent successfully to the server was 3,615 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2050) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:414) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java) ~[HikariCP-4.0.3.jar:?]
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.begin(AbstractLogicalConnectionImplementor.java:72) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:285) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:71) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandCounterInterceptor.execute(CommandCounterInterceptor.java:35) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.ExceptionCodeInterceptor.execute(ExceptionCodeInterceptor.java:55) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.ManagementServiceImpl.unregisterProcessApplication(ManagementServiceImpl.java:125) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.container.impl.deployment.UndeployProcessArchiveStep.performOperationStep(UndeployProcessArchiveStep.java:65) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.container.impl.spi.DeploymentOperation.execute(DeploymentOperation.java:120) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.container.impl.jmx.MBeanServiceContainer.executeDeploymentOperation(MBeanServiceContainer.java:160) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.container.impl.spi.DeploymentOperation$DeploymentOperationBuilder.execute(DeploymentOperation.java:216) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.container.impl.RuntimeContainerDelegateImpl.undeployProcessApplication(RuntimeContainerDelegateImpl.java:124) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.application.AbstractProcessApplication.undeploy(AbstractProcessApplication.java:86) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.spring.application.SpringProcessApplication.stop(SpringProcessApplication.java:114) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.spring.application.SpringProcessApplication.destroy(SpringProcessApplication.java:124) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.spring.boot.starter.SpringBootProcessApplication.destroy(SpringBootProcessApplication.java:107) ~[camunda-bpm-spring-boot-starter-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.spring.application.SpringProcessApplication.onApplicationEvent(SpringProcessApplication.java:99) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.spring.application.SpringProcessApplication.onApplicationEvent(SpringProcessApplication.java:52) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.spring.boot.starter.SpringBootProcessApplication$$EnhancerBySpringCGLIB$$1378b460.onApplicationEvent(<generated>) ~[camunda-bpm-spring-boot-starter-7.18.0.jar:7.18.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1058) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:172) ~[spring-boot-2.6.12.jar:2.6.12]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.admin.SpringApplicationAdminMXBeanRegistrar$SpringApplicationAdmin.shutdown(SpringApplicationAdminMXBeanRegistrar.java:160) ~[spring-boot-2.6.12.jar:2.6.12]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:262) ~[?:?]
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193) ~[?:?]
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175) ~[?:?]
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117) ~[?:?]
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54) ~[?:?]
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237) ~[?:?]
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138) ~[?:?]
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252) ~[?:?]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:814) ~[?:?]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:802) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1472) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1310) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1405) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360) ~[?:?]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[?:?]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 2,881 milliseconds ago. The last packet sent successfully to the server was 3,615 milliseconds ago.
	at jdk.internal.reflect.GeneratedConstructorAccessor133.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:581) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:761) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:700) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1051) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:663) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2033) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	... 76 more
Caused by: java.net.SocketException: Connection reset
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1460) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064) ~[?:?]
	at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:575) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:761) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:700) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1051) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:663) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2033) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	... 76 more
[2023-08-03 12:23:38,687] - [org.camunda.bpm.container] [logError] -> (ERROR) [ENGINE-08044 Exception while performing 'Undeploying process archvie null': Could not open JPA EntityManager for transaction; nested exception is org.hibernate.TransactionException: JDBC begin transaction failed: ] 
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.TransactionException: JDBC begin transaction failed: 
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:467) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:71) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandCounterInterceptor.execute(CommandCounterInterceptor.java:35) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.ExceptionCodeInterceptor.execute(ExceptionCodeInterceptor.java:55) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.ManagementServiceImpl.unregisterProcessApplication(ManagementServiceImpl.java:125) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.container.impl.deployment.UndeployProcessArchiveStep.performOperationStep(UndeployProcessArchiveStep.java:65) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.container.impl.spi.DeploymentOperation.execute(DeploymentOperation.java:120) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.container.impl.jmx.MBeanServiceContainer.executeDeploymentOperation(MBeanServiceContainer.java:160) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.container.impl.spi.DeploymentOperation$DeploymentOperationBuilder.execute(DeploymentOperation.java:216) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.container.impl.RuntimeContainerDelegateImpl.undeployProcessApplication(RuntimeContainerDelegateImpl.java:124) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.application.AbstractProcessApplication.undeploy(AbstractProcessApplication.java:86) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.spring.application.SpringProcessApplication.stop(SpringProcessApplication.java:114) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.spring.application.SpringProcessApplication.destroy(SpringProcessApplication.java:124) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.spring.boot.starter.SpringBootProcessApplication.destroy(SpringBootProcessApplication.java:107) ~[camunda-bpm-spring-boot-starter-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.spring.application.SpringProcessApplication.onApplicationEvent(SpringProcessApplication.java:99) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.spring.application.SpringProcessApplication.onApplicationEvent(SpringProcessApplication.java:52) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.spring.boot.starter.SpringBootProcessApplication$$EnhancerBySpringCGLIB$$1378b460.onApplicationEvent(<generated>) ~[camunda-bpm-spring-boot-starter-7.18.0.jar:7.18.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1058) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:172) ~[spring-boot-2.6.12.jar:2.6.12]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.admin.SpringApplicationAdminMXBeanRegistrar$SpringApplicationAdmin.shutdown(SpringApplicationAdminMXBeanRegistrar.java:160) ~[spring-boot-2.6.12.jar:2.6.12]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:262) ~[?:?]
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193) ~[?:?]
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175) ~[?:?]
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117) ~[?:?]
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54) ~[?:?]
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237) ~[?:?]
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138) ~[?:?]
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252) ~[?:?]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:814) ~[?:?]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:802) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1472) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1310) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1405) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360) ~[?:?]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[?:?]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.hibernate.TransactionException: JDBC begin transaction failed: 
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.begin(AbstractLogicalConnectionImplementor.java:78) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:285) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.23.jar:5.3.23]
	... 68 more
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 2,881 milliseconds ago. The last packet sent successfully to the server was 3,615 milliseconds ago.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2050) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:414) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java) ~[HikariCP-4.0.3.jar:?]
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.begin(AbstractLogicalConnectionImplementor.java:72) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:285) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.23.jar:5.3.23]
	... 68 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 2,881 milliseconds ago. The last packet sent successfully to the server was 3,615 milliseconds ago.
	at jdk.internal.reflect.GeneratedConstructorAccessor133.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:581) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:761) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:700) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1051) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:663) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2033) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:414) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java) ~[HikariCP-4.0.3.jar:?]
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.begin(AbstractLogicalConnectionImplementor.java:72) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:285) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.23.jar:5.3.23]
	... 68 more
Caused by: java.net.SocketException: Connection reset
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1460) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064) ~[?:?]
	at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:575) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:761) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:700) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1051) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:663) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2033) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:414) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java) ~[HikariCP-4.0.3.jar:?]
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.begin(AbstractLogicalConnectionImplementor.java:72) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:285) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.23.jar:5.3.23]
	... 68 more
[2023-08-03 12:23:38,886] - [org.camunda.bpm.container] [logInfo] -> (INFO) [ENGINE-08051 Process application trainingWorkflowApplication undeployed] 
[2023-08-03 12:23:38,965] - [org.apache.coyote.http11.Http11NioProtocol] [log] -> (INFO) [Pausing ProtocolHandler ["http-nio-9002"]] 
[2023-08-03 12:23:38,965] - [org.apache.catalina.core.StandardService] [log] -> (INFO) [Stopping service [Tomcat]] 
[2023-08-03 12:23:38,984] - [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]] [log] -> (INFO) [Destroying Spring FrameworkServlet 'dispatcherServlet'] 
[2023-08-03 12:23:39,047] - [org.apache.coyote.http11.Http11NioProtocol] [log] -> (INFO) [Stopping ProtocolHandler ["http-nio-9002"]] 
[2023-08-03 12:23:39,053] - [org.apache.coyote.http11.Http11NioProtocol] [log] -> (INFO) [Destroying ProtocolHandler ["http-nio-9002"]] 
[2023-08-03 12:24:09,084] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (WARN) [SQL Error: 0, SQLState: 08S01] 
[2023-08-03 12:24:09,085] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (ERROR) [HikariPool-1 - Connection is not available, request timed out after 30009ms.] 
[2023-08-03 12:24:09,085] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (ERROR) [Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.] 
[2023-08-03 12:24:09,089] - [org.camunda.bpm.engine.metrics] [logWarn] -> (WARN) [ENGINE-18001 Could not collect and log metrics] 
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:467) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:71) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandCounterInterceptor.execute(CommandCounterInterceptor.java:35) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.ExceptionCodeInterceptor.execute(ExceptionCodeInterceptor.java:55) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.metrics.reporter.MetricsCollectionTask.collectMetrics(MetricsCollectionTask.java:76) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.metrics.reporter.MetricsCollectionTask.run(MetricsCollectionTask.java:53) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.metrics.reporter.DbMetricsReporter.reportNow(DbMetricsReporter.java:76) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.metrics.reporter.DbMetricsReporter.stop(DbMetricsReporter.java:70) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.ProcessEngineImpl.close(ProcessEngineImpl.java:171) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.spring.ProcessEngineFactoryBean.destroy(ProcessEngineFactoryBean.java:42) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:213) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1163) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1156) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:172) ~[spring-boot-2.6.12.jar:2.6.12]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.admin.SpringApplicationAdminMXBeanRegistrar$SpringApplicationAdmin.shutdown(SpringApplicationAdminMXBeanRegistrar.java:160) ~[spring-boot-2.6.12.jar:2.6.12]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:262) ~[?:?]
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193) ~[?:?]
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175) ~[?:?]
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117) ~[?:?]
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54) ~[?:?]
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237) ~[?:?]
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138) ~[?:?]
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252) ~[?:?]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:814) ~[?:?]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:802) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1472) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1310) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1405) ~[?:?]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360) ~[?:?]
	at sun.rmi.transport.Transport$1.run(Transport.java:200) ~[?:?]
	at sun.rmi.transport.Transport$1.run(Transport.java:197) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:276) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:284) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.23.jar:5.3.23]
	... 63 more
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30009ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-4.0.3.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:276) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:284) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.23.jar:5.3.23]
	... 63 more
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-4.0.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	... 3 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at jdk.internal.reflect.GeneratedConstructorAccessor133.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-4.0.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	... 3 more
Caused by: java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-4.0.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	... 3 more
[2023-08-03 12:24:11,818] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (WARN) [SQL Error: 0, SQLState: 08S01] 
[2023-08-03 12:24:11,820] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (ERROR) [HikariPool-1 - Connection is not available, request timed out after 30054ms.] 
[2023-08-03 12:24:11,821] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (ERROR) [Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.] 
[2023-08-03 12:24:11,822] - [org.camunda.bpm.engine.jobexecutor] [logError] -> (ERROR) [ENGINE-14019 Exception during job acquisition Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection] 
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:467) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137) ~[spring-tx-5.3.23.jar:5.3.23]
	at org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:71) ~[camunda-engine-spring-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandCounterInterceptor.execute(CommandCounterInterceptor.java:35) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.interceptor.ExceptionCodeInterceptor.execute(ExceptionCodeInterceptor.java:55) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.jobexecutor.SequentialJobAcquisitionRunnable.acquireJobs(SequentialJobAcquisitionRunnable.java:164) ~[camunda-engine-7.18.0.jar:7.18.0]
	at org.camunda.bpm.engine.impl.jobexecutor.SequentialJobAcquisitionRunnable.run(SequentialJobAcquisitionRunnable.java:80) ~[camunda-engine-7.18.0.jar:7.18.0]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:276) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:284) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.23.jar:5.3.23]
	... 11 more
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30054ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-4.0.3.jar:?]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:276) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:284) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83) ~[hibernate-core-5.6.11.Final.jar:5.6.11.Final]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:164) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:421) ~[spring-orm-5.3.23.jar:5.3.23]
	... 11 more
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-4.0.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at jdk.internal.reflect.GeneratedConstructorAccessor133.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-4.0.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-4.0.3.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
[2023-08-03 12:24:39,097] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (WARN) [SQL Error: 0, SQLState: 08S01] 
[2023-08-03 12:24:39,098] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (ERROR) [HikariPool-1 - Connection is not available, request timed out after 30011ms.] 
[2023-08-03 12:24:39,100] - [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] [logExceptions] -> (ERROR) [Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.] 
[2023-08-03 12:24:39,105] - [org.springframework.beans.factory.support.DisposableBeanAdapter] [destroy] -> (WARN) [Invocation of destroy method failed on bean with name 'processEngineFactoryBean': org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection] 
[2023-08-03 12:24:39,115] - [org.camunda.bpm.engine.jobexecutor] [logInfo] -> (INFO) [ENGINE-14015 Shutting down the JobExecutor[org.camunda.bpm.engine.spring.components.jobexecutor.SpringJobExecutor]] 
[2023-08-03 12:24:39,115] - [org.camunda.bpm.engine.jobexecutor] [logInfo] -> (INFO) [ENGINE-14020 JobExecutor[org.camunda.bpm.engine.spring.components.jobexecutor.SpringJobExecutor] stopped job acquisition] 
[2023-08-03 12:24:39,117] - [org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean] [destroy] -> (INFO) [Closing JPA EntityManagerFactory for persistence unit 'default'] 
[2023-08-03 12:24:39,126] - [com.zaxxer.hikari.HikariDataSource] [close] -> (INFO) [HikariPool-1 - Shutdown initiated...] 
[2023-08-03 12:25:00,935] - [com.zaxxer.hikari.HikariDataSource] [close] -> (INFO) [HikariPool-1 - Shutdown completed.] 
